Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-08c40ec9ead489470
      Tags:
        - Key: "Name"
          Value: "Change1"